# Generated by Django 3.1.2 on 2020-10-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidoPaterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellidoMaterno', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('numeroTelefono', models.IntegerField(max_length=50, verbose_name='Número de teléfono')),
                ('fechaNacimiento', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('fechaIngreso', models.DateTimeField(verbose_name='Fecha de ingreso al trabajo')),
            ],
        ),
    ]
