# Generated by Django 3.1.2 on 2020-10-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='numeroTelefono',
            field=models.IntegerField(verbose_name='Número de teléfono'),
        ),
    ]
