# Generated by Django 3.1.2 on 2020-10-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20201022_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='fechaIngreso',
            field=models.DateField(verbose_name='Fecha de ingreso al trabajo'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='numeroTelefono',
            field=models.CharField(max_length=20, verbose_name='Número de teléfono'),
        ),
    ]
