# Generated by Django 3.1.2 on 2020-10-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20201022_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajasLimon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limonVerdeLunes', models.CharField(max_length=20, verbose_name='Lunes cantidad de limón verde')),
                ('limonManchadoLunes', models.CharField(max_length=20, verbose_name='Cantidad de limón manchado')),
                ('limonVerdeMartes', models.CharField(max_length=20, verbose_name='Martes cantidad de limón verde')),
                ('limonManchadoMartes', models.CharField(max_length=20, verbose_name='Cantidad de limón manchado')),
                ('limonVerdeMiercoles', models.CharField(max_length=20, verbose_name='Miércoles cantidad de limón verde')),
                ('limonManchadoMiercoles', models.CharField(max_length=20, verbose_name='Cantidad de limón manchado')),
                ('limonVerdeJueves', models.CharField(max_length=20, verbose_name='Jueves cantidad de limón verde')),
                ('limonManchadoJueves', models.CharField(max_length=20, verbose_name='Cantidad de limón manchado')),
                ('limonVerdeViernes', models.CharField(max_length=20, verbose_name='Viernes cantidad de limón verde')),
                ('limonVerdeSabado', models.CharField(max_length=20, verbose_name='Sábado cantidad de limón verde')),
                ('limonManchadoSabado', models.CharField(max_length=20, verbose_name='Cantidad de limón manchado')),
            ],
            options={
                'verbose_name': 'Cantidad entregada de cajas de limón',
            },
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
    ]
