# Generated by Django 3.1.2 on 2020-10-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20201022_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso', models.CharField(max_length=50, verbose_name='Uso')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('nombreHerramienta', models.CharField(max_length=50, verbose_name='Herramienta')),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
            },
        ),
        migrations.AlterModelOptions(
            name='cajaslimon',
            options={'verbose_name': 'Cantidad entregada de cajas de limón (Día)', 'verbose_name_plural': 'Cantidad entregada de cajas de limón (Día)'},
        ),
    ]
