# Generated by Django 3.1.2 on 2020-10-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20201022_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='marca',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='nombreHerramienta',
            field=models.CharField(max_length=100, verbose_name='Herramienta'),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='uso',
            field=models.CharField(max_length=100, verbose_name='Uso'),
        ),
    ]
