# Generated by Django 3.1.2 on 2020-10-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20201022_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosQuimicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('funcion', models.CharField(max_length=100, verbose_name='Función del producto químico')),
                ('cantidad', models.CharField(max_length=100, verbose_name='Cantidad por producto')),
                ('componentes', models.CharField(max_length=100, verbose_name='Componentes')),
                ('fechaElaboracion', models.CharField(max_length=100, verbose_name='Fecha de elaboraciónn')),
            ],
            options={
                'verbose_name': 'Producto químico',
                'verbose_name_plural': 'Productos químicos',
            },
        ),
    ]
