# Generated by Django 3.1.2 on 2020-10-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_productosquimicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('function', models.CharField(max_length=100, verbose_name='Función del producto químico')),
                ('quantity', models.CharField(max_length=100, verbose_name='Cantidad por producto')),
                ('components', models.CharField(max_length=100, verbose_name='Componentes')),
                ('dateElaboration', models.CharField(max_length=100, verbose_name='Fecha de elaboraciónn')),
            ],
            options={
                'verbose_name': 'Producto químico',
                'verbose_name_plural': 'Productos químicos',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('firtsname', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('secondname', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('numberPhone', models.CharField(max_length=20, verbose_name='Número de teléfono')),
                ('birthday', models.DateField(verbose_name='Fecha de nacimiento')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('entry', models.DateField(verbose_name='Fecha de ingreso al trabajo')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='LemonBoxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greenLemonMonday', models.CharField(max_length=20, verbose_name='Lunes cantidad de limón verde')),
                ('stainedLemonMonday', models.CharField(max_length=20, verbose_name='Cantidad de limón manchado')),
                ('greenLemonTuesday', models.CharField(max_length=20, verbose_name='Martes cantidad de limón verde')),
                ('stainedLemonTuesday', models.CharField(max_length=20, verbose_name='Cantidad de limón manchado')),
                ('greenLemonWednesday', models.CharField(max_length=20, verbose_name='Miércoles cantidad de limón verde')),
                ('stainedLemonWednesday', models.CharField(max_length=20, verbose_name='Cantidad de limón manchado')),
                ('greenLemonThursday', models.CharField(max_length=20, verbose_name='Jueves cantidad de limón verde')),
                ('stainedLemonThursday', models.CharField(max_length=20, verbose_name='Cantidad de limón manchado')),
                ('greenLemonFriday', models.CharField(max_length=20, verbose_name='Viernes cantidad de limón verde')),
                ('stainedLemonFriday', models.CharField(max_length=20, verbose_name='Cantidad de limón manchado')),
                ('greenLemonSaturday', models.CharField(max_length=20, verbose_name='Sábado cantidad de limón verde')),
                ('stainedLemonSaturday', models.CharField(max_length=20, verbose_name='Cantidad de limón manchado')),
            ],
            options={
                'verbose_name': 'Cantidad entregada de cajas de limón (Día)',
                'verbose_name_plural': 'Cantidad entregada de cajas de limón (Día)',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(max_length=100, verbose_name='Uso')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('nameTool', models.CharField(max_length=100, verbose_name='Herramienta')),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
            },
        ),
        migrations.DeleteModel(
            name='CajasLimon',
        ),
        migrations.DeleteModel(
            name='Herramienta',
        ),
        migrations.DeleteModel(
            name='ProductosQuimicos',
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
