# Generated by Django 3.1.2 on 2020-10-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20201022_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalproducts',
            name='dateElaboration',
            field=models.CharField(max_length=100, verbose_name='Fecha de caducidad'),
        ),
    ]
