# Generated by Django 3.1.2 on 2020-11-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20201029_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lemonboxes',
            options={'verbose_name': 'Entrega de carga', 'verbose_name_plural': 'Entrega de cajas'},
        ),
        migrations.AddField(
            model_name='lemonboxes',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='NOMBRE DEL TRABAJADOR'),
            preserve_default=False,
        ),
    ]
